Repository Dessia-tech/plot_data, pull requests merged in 2024-03, with the labels that each got.

#360 fix local import
  CHANGELOG.md
  plot_data/core.py
Labels: type: bug, priority: critical

#372 fix/add_plot_no_name_2
  CHANGELOG.md
  src/multiplot.ts
Labels: status: done

#374 Fix/html
  CHANGELOG.md
  cypress/e2e/visualRegressions.cy.ts
  cypress/snapshots/base/visualRegressions.cy.ts/GRAPH2D -- should draw a nice horizontal parallel plot-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/GRAPH2D -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/HISTOGRAM -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/MULTIPLOT -- should draw a canvas with text of empty data-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/MULTIPLOT -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/PARALLELPLOT -- should draw a nice horizontal parallel plot-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/PARALLELPLOT -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/PLOTSCATTER -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/PRIMITIVEGROUPCONTAINER -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/SCATTERMATRIX -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/SIMPLESHAPES -- should draw canvas-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/SIMPLESHAPES -- should draw tooltip on line-base.png
  cypress/snapshots/base/visualRegressions.cy.ts/TEXTSCALING -- should draw canvas-base.png
  cypress/templates/emptyMultiplot.template.html
  cypress/templates/graph2d.template.html
  cypress/templates/histogram.template.html
  cypress/templates/multiplot.template.html
  cypress/templates/parallelplot.template.html
  cypress/templates/plotscatter.template.html
  cypress/templates/primitivegroupcontainer.template.html
  cypress/templates/scattermatrix.template.html
  cypress/templates/simpleshapes.template.html
  cypress/templates/textscaling.template.html
  plot_data/templates.py
Labels: type: enhancement, status: done, priority: high

#370 Fix LineSegment edge_style when using mpl_plot
  CHANGELOG.md
  plot_data/core.py
Labels: status: done

#376 add fix to Arc2D: mpl_plot
  CHANGELOG.md
  plot_data/core.py
Labels: status: done
